name: Build Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Task
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run electron:build

